### ISSUE TITLE
explode while installing  

### ISSUE THREAD

**Issue by MousaAlshaikh** [umartinez22/python-huawei-cloud-messaging#7]
Using pip 20.2.4 from /home/mousa/Sites/HMS/HMS_ENV/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-ephem-wheel-cache-vfdhqrc7
Created temporary directory: /tmp/pip-req-tracker-qtgewncw
Initialized build tracking at /tmp/pip-req-tracker-qtgewncw
Created build tracker: /tmp/pip-req-tracker-qtgewncw
Entered build tracker: /tmp/pip-req-tracker-qtgewncw
Created temporary directory: /tmp/pip-install-bz7fsyeo
1 location(s) to search for versions of pyhcm:
* https://pypi.org/simple/pyhcm/
Fetching project page and analyzing links: https://pypi.org/simple/pyhcm/
Getting page https://pypi.org/simple/pyhcm/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/pyhcm/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pyhcm/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/9d/67/82511c234dc9aff49afaa7ef6d4ee817a7bf08f4b26689d365d5eff2efac/pyhcm-1.0.2.tar.gz#sha256=d36b401b78015173491889f4db47dc9edaf30211b6480584a7d85012dc358129 (from https://pypi.org/simple/pyhcm/), version: 1.0.2
  Found link https://files.pythonhosted.org/packages/e9/94/7a316a1033539bd93899bdcf981dac1a7a9615271ea3ebb0e138d6a16968/pyhcm-1.0.4.tar.gz#sha256=432084f809499ebccc891541f5ad7e4191570cdb0a8b59153121b2d802a71b98 (from https://pypi.org/simple/pyhcm/), version: 1.0.4
  Found link https://files.pythonhosted.org/packages/92/54/d7cc9e63ac7e6fcc9e7cb497bd8f18e9c9f7e85092dd9414c6aa967e6207/pyhcm-1.0.5.tar.gz#sha256=129c42cd60b831ade3e085ea77c879bf40a7c88694fbcd833c547734b5cec76d (from https://pypi.org/simple/pyhcm/), version: 1.0.5
  Found link https://files.pythonhosted.org/packages/70/87/c5f7cb096d6276642991e01b3eb46e8286ed7dd76c4ef24db37b177eb9da/pyhcm-1.0.6.1.tar.gz#sha256=3bf57577a4121774e1bdab06acde17f790400909d6add3924a59ed5cdd0aac8b (from https://pypi.org/simple/pyhcm/), version: 1.0.6.1
  Found link https://files.pythonhosted.org/packages/3c/04/4cd9c66918ce8cf625e2de0c3379a375fac126b51b40a6fc65ce42dd000a/pyhcm-1.0.6.3.tar.gz#sha256=50e6c3cab788311b1038cfcfce607c238795a6adf58e7425dc57eaa6ed9de868 (from https://pypi.org/simple/pyhcm/), version: 1.0.6.3
Given no hashes to check 5 links for project 'pyhcm': discarding no candidates
Using version 1.0.6.3 (newest of versions: 1.0.2, 1.0.4, 1.0.5, 1.0.6.1, 1.0.6.3)
Collecting pyhcm
  Created temporary directory: /tmp/pip-unpack-h1ueo1qw
  Looking up "https://files.pythonhosted.org/packages/3c/04/4cd9c66918ce8cf625e2de0c3379a375fac126b51b40a6fc65ce42dd000a/pyhcm-1.0.6.3.tar.gz" in the cache
  Current age based on date: 142
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 142
  Using cached pyhcm-1.0.6.3.tar.gz (2.6 kB)
  Added pyhcm from https://files.pythonhosted.org/packages/3c/04/4cd9c66918ce8cf625e2de0c3379a375fac126b51b40a6fc65ce42dd000a/pyhcm-1.0.6.3.tar.gz#sha256=50e6c3cab788311b1038cfcfce607c238795a6adf58e7425dc57eaa6ed9de868 to build tracker '/tmp/pip-req-tracker-qtgewncw'
    Running setup.py (path:/tmp/pip-install-bz7fsyeo/pyhcm/setup.py) egg_info for package pyhcm
    Created temporary directory: /tmp/pip-pip-egg-info-exu3_jws
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bz7fsyeo/pyhcm/setup.py", line 9, in <module>
        with open(path.join(current_directory, 'README.md'), encoding='utf-8') as file:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-bz7fsyeo/pyhcm/README.md'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/mousa/Sites/HMS/HMS_ENV/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/home/mousa/Sites/HMS/HMS_ENV/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/mousa/Sites/HMS/HMS_ENV/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "/home/mousa/Sites/HMS/HMS_ENV/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/mousa/Sites/HMS/HMS_ENV/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/mousa/Sites/HMS/HMS_ENV/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/mousa/Sites/HMS/HMS_ENV/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/home/mousa/Sites/HMS/HMS_ENV/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/mousa/Sites/HMS/HMS_ENV/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/home/mousa/Sites/HMS/HMS_ENV/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/home/mousa/Sites/HMS/HMS_ENV/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 530, in _generate_metadata
    return generate_metadata_legacy(
  File "/home/mousa/Sites/HMS/HMS_ENV/lib/python3.8/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 70, in generate_metadata
    call_subprocess(
  File "/home/mousa/Sites/HMS/HMS_ENV/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.4; however, version 20.3.3 is available.
You should consider upgrading via the '/home/mousa/Sites/HMS/HMS_ENV/bin/python -m pip install --upgrade pip' command.
Removed pyhcm from https://files.pythonhosted.org/packages/3c/04/4cd9c66918ce8cf625e2de0c3379a375fac126b51b40a6fc65ce42dd000a/pyhcm-1.0.6.3.tar.gz#sha256=50e6c3cab788311b1038cfcfce607c238795a6adf58e7425dc57eaa6ed9de868 from build tracker '/tmp/pip-req-tracker-qtgewncw'
Removed build tracker: '/tmp/pip-req-tracker-qtgewncw'

**Comment by umartinez22** [comment]
@MousaAlshaikh Thank you for the report, I already upload some changes to resolve this error, please install this new version **(pip install pyhcm==1.0.6.4)**

**Comment by MousaAlshaikh** [comment]
Great it works fine, Thank you
